version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
  deploy:
    executor:
      name: node/default
    parameters:
      stage_name:
        type: string
    steps:
      - checkout

      - node/with-cache:
          steps:
            - run: npm install

      - run:
          name: sls deploy
          command: npm run deploy -- -s << parameters.stage_name >>
  integration-test:
    executor:
      name: node/default
    parameters:
      stage_name:
        type: string
    steps:
      - run:
          name: integration-tests
          command: |
            export INTEGRATION_TEST_BASE_URL=$(echo $(npx serverless info -s << parameters.stage_name >> | grep -o -m 1 "https://.*$"))
            npm run test:integration

workflows:
  continuous-delivery:
    jobs:
      - build-and-test
      - deploy:
          name: deploy-production
          stage_name: prod
          context: housing-needs-development-context
          filters:
            branches:
              only: master
      - deploy:
          name: deploy-temporary-branch
          stage_name: ${CIRCLE_BRANCH##*/}
          context: housing-needs-development-context
          filters:
            branches:
              ignore: master
          requires:
            - build-and-test
      - integration-test:
          name: integration-test
          stage_name: ${CIRCLE_BRANCH##*/}
          context: housing-needs-development-context
          filters:
            branches:
              ignore: master
          requires:
            - deploy-temporary-branch
