version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-cli: circleci/aws-cli@1.0.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm i
            - run: npm run build
            - run: npm test
      - store_artifacts:
          path: coverage
      - persist_to_workspace:
          root: ~/
          paths: .

  deploy:
    executor:
      name: node/default
    parameters:
      stage_name:
        type: string
    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: sls deploy
          command: |
            npm prune --production
            sudo npm i -g serverless
            serverless deploy -s << parameters.stage_name >>

  integration-test:
    executor:
      name: node/default
    parameters:
      stage_name:
        type: string
    steps:
      - attach_workspace:
          at: ~/
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - run:
          name: integration-tests
          command: |
            node lib/index.js &
            export INTEGRATION_TEST_BASE_URL=http://localhost:5050
            npm run test:integration

workflows:
  continuous-delivery:
    jobs:
      - build-and-test
      - deploy:
          name: build-deploy-staging
          context: housing-needs-development-context
          stage_name: staging
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
      - permit:
          name: permit-deploy-production
          context: housing-needs-development-context
          type: approval
          requires:
            - build-deploy-staging
      - deploy:
          name: deploy-production
          stage_name: prod
          context: housing-needs-development-context
          filters:
            branches:
              only: master
          requires:
            - permit-deploy-production
      - integration-test:
          name: integration-test
          stage_name: ${CIRCLE_BRANCH##*/}
          context: housing-needs-development-context
          filters:
            branches:
              ignore: master
          requires:
            - build-and-test
